-- Seed Courses from NAMAC Course List
-- Run this in Supabase SQL Editor

-- Insert maritime training courses
INSERT INTO courses (
  title,
  type,
  category,
  duration,
  mode,
  fees,
  description,
  course_overview,
  target_audience,
  entry_requirements,
  validity_months,
  currency,
  status
) VALUES
  (
    'Basic Safety Training (BST)',
    'STCW',
    'Safety',
    '5 Days',
    'offline',
    15000,
    'Basic Safety Training course covering essential maritime safety skills',
    'Comprehensive training in personal survival techniques, fire prevention and firefighting, elementary first aid, and personal safety and social responsibilities.',
    'All seafarers working on ships',
    'Must be 18 years or above. Medical fitness certificate required.',
    60,
    'INR',
    'active'
  ),
  (
    'Advanced Fire Fighting (AFF)',
    'STCW',
    'Safety',
    '3 Days',
    'offline',
    12000,
    'Advanced training in fire prevention and firefighting techniques',
    'Advanced level training for officers responsible for controlling fire fighting operations aboard ships.',
    'Ship officers and crew members with fire fighting responsibilities',
    'Valid Basic Fire Fighting certificate. Medical fitness required.',
    60,
    'INR',
    'active'
  ),
  (
    'Medical First Aid (MFA)',
    'STCW',
    'Medical',
    '3 Days',
    'offline',
    10000,
    'First aid training for maritime personnel',
    'Training in immediate care and treatment of injuries and illnesses on board ships.',
    'All seafarers',
    'Basic Safety Training certificate. Medical fitness required.',
    60,
    'INR',
    'active'
  ),
  (
    'Medical Care on Board Ship',
    'STCW',
    'Medical',
    '5 Days',
    'offline',
    18000,
    'Advanced medical care training for ship personnel',
    'Comprehensive medical care training for those designated to take charge of medical care on board.',
    'Ship officers designated for medical care duties',
    'Valid Medical First Aid certificate. Medical fitness required.',
    60,
    'INR',
    'active'
  ),
  (
    'Proficiency in Survival Craft and Rescue Boats (PSCRB)',
    'STCW',
    'Safety',
    '5 Days',
    'offline',
    16000,
    'Training in survival craft and rescue boat operations',
    'Training for seafarers designated to take charge of survival craft and rescue boats.',
    'Deck officers and crew members with lifeboat responsibilities',
    'Valid Basic Safety Training certificate. Medical fitness required.',
    60,
    'INR',
    'active'
  ),
  (
    'Ship Security Officer (SSO)',
    'STCW',
    'Security',
    '3 Days',
    'offline',
    14000,
    'Security training for designated ship security officers',
    'Training for personnel designated as Ship Security Officers under ISPS Code.',
    'Officers designated as Ship Security Officers',
    'Valid Basic Safety Training. Minimum 1 year sea service.',
    60,
    'INR',
    'active'
  ),
  (
    'Designated Security Duties (DSD)',
    'STCW',
    'Security',
    '2 Days',
    'offline',
    8000,
    'Security awareness training for crew with designated security duties',
    'Training for seafarers designated to perform security duties on board ships.',
    'All crew members with security responsibilities',
    'Valid Basic Safety Training certificate.',
    60,
    'INR',
    'active'
  ),
  (
    'GMDSS General Operator Certificate (GOC)',
    'STCW',
    'Communication',
    '14 Days',
    'offline',
    35000,
    'Global Maritime Distress and Safety System training',
    'Comprehensive training in GMDSS radio equipment operation and procedures.',
    'Radio officers and deck officers',
    'Basic education in mathematics and physics. Valid BST certificate.',
    60,
    'INR',
    'active'
  ),
  (
    'Automatic Radar Plotting Aids (ARPA)',
    'STCW',
    'Navigation',
    '5 Days',
    'offline',
    20000,
    'Training in automatic radar plotting aids',
    'Training in the use of ARPA and radar for safe navigation.',
    'Navigating officers',
    'Valid Radar Navigation certificate. Minimum 6 months sea service.',
    60,
    'INR',
    'active'
  ),
  (
    'Electronic Chart Display and Information System (ECDIS)',
    'STCW',
    'Navigation',
    '5 Days',
    'offline',
    22000,
    'Training in electronic chart systems',
    'Generic and specific training in the use of ECDIS for safe navigation.',
    'Deck officers responsible for navigation',
    'Valid certificate of competency. Minimum 6 months sea service.',
    60,
    'INR',
    'active'
  ),
  (
    'Bridge Resource Management (BRM)',
    'STCW',
    'Management',
    '3 Days',
    'offline',
    15000,
    'Bridge team management and resource management training',
    'Training in effective bridge team management, communication, and decision making.',
    'Deck officers and masters',
    'Valid certificate of competency. Minimum 12 months sea service.',
    60,
    'INR',
    'active'
  ),
  (
    'Engine Resource Management (ERM)',
    'STCW',
    'Management',
    '3 Days',
    'offline',
    15000,
    'Engine room team management training',
    'Training in effective engine room team management and resource utilization.',
    'Engineer officers',
    'Valid certificate of competency. Minimum 12 months sea service.',
    60,
    'INR',
    'active'
  ),
  (
    'Tanker Familiarization',
    'STCW',
    'Specialized',
    '2 Days',
    'offline',
    10000,
    'Familiarization training for tanker operations',
    'Basic training for all personnel working on oil and chemical tankers.',
    'All crew members on tankers',
    'Valid Basic Safety Training certificate.',
    60,
    'INR',
    'active'
  ),
  (
    'Oil Tanker - Advanced Training',
    'STCW',
    'Specialized',
    '5 Days',
    'offline',
    25000,
    'Advanced training for oil tanker operations',
    'Advanced level training for officers on oil tankers.',
    'Deck and engineer officers on oil tankers',
    'Valid Tanker Familiarization. Minimum 3 months tanker experience.',
    60,
    'INR',
    'active'
  ),
  (
    'Chemical Tanker - Advanced Training',
    'STCW',
    'Specialized',
    '5 Days',
    'offline',
    25000,
    'Advanced training for chemical tanker operations',
    'Advanced level training for officers on chemical tankers.',
    'Deck and engineer officers on chemical tankers',
    'Valid Tanker Familiarization. Minimum 3 months tanker experience.',
    60,
    'INR',
    'active'
  ),
  (
    'Liquefied Gas Tanker - Advanced Training',
    'STCW',
    'Specialized',
    '5 Days',
    'offline',
    28000,
    'Advanced training for LNG/LPG tanker operations',
    'Advanced level training for officers on liquefied gas tankers.',
    'Deck and engineer officers on gas tankers',
    'Valid Tanker Familiarization. Minimum 3 months tanker experience.',
    60,
    'INR',
    'active'
  );

-- Verify the insert
SELECT COUNT(*) as total_courses FROM courses;
SELECT title, type, category, fees, currency FROM courses ORDER BY created_at DESC LIMIT 10;
